### PR TITLE
eelsdb blocks requests bugfix

### PR DESCRIPTION
**Pull request by PauTorru**
### Description of the change
A few sentences and/or a bulleted list to describe and motivate the change:
-  Added headers to request.get calls to eelsdb

### Progress of the PR
- [ ] Change implemented (can be split into several points),
- [ ] docstring updated (if appropriate),
- [ ] update user guide (if appropriate),
- [ ] added tests,
- [ ] add a changelog entry in the `upcoming_changes` folder (see [`upcoming_changes/README.rst`](https://github.com/hyperspy/exspy/blob/main/upcoming_changes/README.rst)),
- [ ] Check formatting of the changelog entry (and eventual user guide changes) in the `docs/readthedocs.org:exspy` build of this PR (link in github checks)
- [ ] ready for review.

### Minimal example of the bug fix or the new feature
```python
from exspy.misc.eels import eelsdb
s = eelsdb.eelsdb(spectrum_type="coreloss",element="O",edge="K")
```

### CODE REVIEW

**Comment by ericpre** [comment]
pre-commit.ci autofix

**Review by ericpre — COMMENTED** [review]
Can you add a changelog entry as described in the pull request template:
https://github.com/hyperspy/exspy/blob/main/.github/PULL_REQUEST_TEMPLATE.md

**Comment by PauTorru** [comment]
> Can you add a changelog entry as described in the pull request template: https://github.com/hyperspy/exspy/blob/main/.github/PULL_REQUEST_TEMPLATE.md

Like so? I edited first coment

**Comment by ericpre** [comment]
For the changelog entry, you need to add a `rst` file summarising the changes and with the correct name. This is explained in more detailed in [upcoming_changes/README.rst](https://github.com/hyperspy/exspy/blob/main/upcoming_changes/README.rst). 

Here is an example of a commit adding a changelog entry: https://github.com/hyperspy/exspy/pull/33/commits/bae38825badc9396e05eb6f16954eeba0684ec8f

The template is here as a guideline, which explains the main steps for contributors to know what they need to do but also as a reminder / check list (including experienced contributors 😄).

**Comment by PauTorru** [comment]
I think I got it now. Easy to tell it was my first contribution. 😅

**Review by ericpre — APPROVED** [review]

**Comment by ericpre** [comment]
Thank you @PauTorru.
There are a number of things to figure out when contributing the first time and it is not always easy to appreciate what is necessary or not, its relevance, etc.! :)

**Pull request merged**
